trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) --var client_secret=$(client_secret) -var ssh-public_key=$(ssh-public_key)'
    backendType: 'azurerm'
    backendServiceArm: 'Azure-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-rja-rg'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'rajeshjallustore'
    backendAzureRmContainerName: 'rajeshjallustorecotainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'azure_rsa.pub'

    